---
- name: Read hosts.txt and create list of VM names
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Read hosts.txt and create a list of VM names
      ansible.builtin.set_fact:
        vm_names: "{{ lookup('file', 'roles/shadowman_provision/files/hosts.txt').splitlines() }}"

    - name: Show the list of VM names
      ansible.builtin.debug:
        var: vm_names[0]

    - name: Gather one specific VM
      community.vmware.vmware_vm_info:
        # hostname: '{{ vcenter_hostname }}'
        # username: '{{ vcenter_username }}'
        # password: '{{ vcenter_password }}'
        vm_name: "{{ item }}"
      loop: "{{ vm_names }}"
